services:
  app:
    build: .
    image: zhf
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=ZillowHomeValueForecast

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ZillowHomeValueForecast
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
